import Head from "next/head";
import Link from "next/link";
import { Heading, Box, Grid } from "@chakra-ui/react";
import {
  FaQuestionCircle,
  FaSistrix,
  FaCloudDownloadAlt,
  FaRegThumbsUp,
  FaClipboardList,
  FaChild,
} from "react-icons/fa";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Group Investigation</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Box className='hero-img'>
          <Box className='inside-container'>
            <Box className='hero-content'>
              <Heading className='h1' mb={"1em"}>
                <span className='line'></span>
                <span className='color'> Group</span> Investigation
              </Heading>

              <Grid
                templateColumns={["repeat(2, 1fr)", "repeat(3, 1fr)"]}
                gap={[8, 24]}
              >
                <Link href='/definitie' passHref>
                  <Box className='icons'>
                    <Box className='icon'>
                      <FaQuestionCircle />
                    </Box>
                    <Box fontSize={["13px", "20px"]} className='onderwerp'>
                      Definitie
                    </Box>
                  </Box>
                </Link>
                <Link href='/achtergrond' passHref>
                  <Box className='icons'>
                    <Box className='icon'>
                      <FaSistrix />
                    </Box>
                    <Box fontSize={["13px", "20px"]} className='onderwerp'>
                      Achtergrond
                    </Box>
                  </Box>
                </Link>
                <Link href='/implementatie' passHref>
                  <Box className='icons'>
                    <Box className='icon'>
                      <FaCloudDownloadAlt />
                    </Box>
                    <Box fontSize={["13px", "20px"]} className='onderwerp'>
                      Implementatie
                    </Box>
                  </Box>
                </Link>
                <Link href='/voorennadelen' passHref>
                  <Box className='icons'>
                    <Box className='icon'>
                      <FaRegThumbsUp />
                    </Box>

                    <Box fontSize={["13px", "20px"]} className='onderwerp'>
                      Voor- en nadelen
                    </Box>
                  </Box>
                </Link>
                <Link href='/randvoorwaarden' passHref>
                  <Box className='icons'>
                    <Box className='icon'>
                      <FaClipboardList />
                    </Box>

                    <Box fontSize={["13px", "20px"]} className='onderwerp'>
                      Randvoorwaarden
                    </Box>
                  </Box>
                </Link>
                <Link href='/praktijkvoorbeeld' passHref>
                  <Box className='icons'>
                    <Box className='icon'>
                      <FaChild />
                    </Box>
                    <Box fontSize={["13px", "20px"]} className='onderwerp'>
                      Praktijkvoorbeeld
                    </Box>
                  </Box>
                </Link>
              </Grid>
            </Box>
          </Box>
        </Box>
      </main>

      <footer>
        <p>Gemaakt door Jonas De Vulder, Pauline Hesters en Imke Loos</p>
      </footer>
    </div>
  );
}
