import Head from "next/head";
import Link from "next/link";
import { Heading, Box, Flex } from "@chakra-ui/react";

export default function Praktijkvoorbeeld() {
  return (
    <div>
      <Head>
        <title>Praktijkvoorbeeld</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Box className='hero-img'>
          <Box className='inside-container'>
            <Box className='hero-content'>
              <Flex justifyContent='center'>
                <Heading className='h1'>
                  <span className='line'></span>{" "}
                  <span className='color'> P</span>
                  raktijkvoorbeeld
                </Heading>
              </Flex>
              <Flex className='nav' justifyContent='center'>
                <Box>
                  <Link href='/' passHref>
                    <span className='navhome'>Terug naar home</span>
                  </Link>
                  /<span className='navactive'>Praktijkvoorbeeld</span>
                </Box>
              </Flex>
              <Box className='content'>
                Het praktijkvoorbeeld dat we hier uitwerken, is een fictief
                voorbeeld dat we zelf ontwierpen. Group investigations laat
                lerenden toe om hun eigen interesses in een onderwerp volledig
                tot hun recht te laten komen. Lerenden gaan namelijk zelf op
                onderzoek. Zo kan bijvoorbeeld in een lerarenopleiding een les
                over didactische werkvormen op die manier vorm krijgen: de klas
                krijgt de opdracht om na te denken over een didactische werkvorm
                die volgens hen goed werkt. In een eerste fase gaan de
                leerlingen het onderwerp verder opdelen in subtopics die hun
                interesseren. Zo kunnen er subtopics ontstaan als didactische
                werkvormen in groep, didactische werkvormen voor wiskunde,
                didactische werkvormen voor zelfstandig werk… Vervolgens
                verdelen de student-leraren zich in verschillende groepjes die
                elk onderzoek zullen doen over één subtopic die hen het meest
                interesseert. In die groepjes maken de studenten een planning en
                een taakverdeling, zodat ieder lid zelfstandig aan de slag kan
                gaan. Op die manier kan het ene lid artikels zoeken over een
                bepaalde werkvorm, terwijl een ander lid haar praktijkervaringen
                met een werkvorm neerschrijft. Wanneer elk lid zijn taak heeft
                volbracht, worden de verschillende resultaten samengebracht tot
                een groepsconclusie. Nadien bereidt de groep een presentatie
                voor waarin ze hun groepsconclusie en bevindingen visualiseren
                door bijvoorbeeld een poster te maken. Ten slotte presenteert
                elke groep hun subtopic aan de volledige klas.{" "}
              </Box>
            </Box>
          </Box>
        </Box>
      </main>

      <footer>
        <p>Gemaakt door Jonas De Vulder, Pauline Hesters en Imke Loos</p>
      </footer>
    </div>
  );
}
